1 One-dimensional arrays

1.1 Creating

In [3]:
L = [11, 7, 19, 22, 55]

In [7]:
import numpy as np
xs = np.array(L)
xs

array([11,  7, 19, 22, 55])

In [9]:
print(xs)

[11  7 19 22 55]


In [11]:
print(L)

[11, 7, 19, 22, 55]


In [13]:
xs.size

5

In [15]:
xs.dtype

dtype('int32')

In [17]:
type(L)

list

In [19]:
type(L[0])

int

In [21]:
type(xs)

numpy.ndarray

In [23]:
type(xs[0])

numpy.int32

In [25]:
ys = np.array([1.1, 2.2, 3.3, 4.4])
ys.dtype

dtype('float64')

In [27]:
zs = np.array([5, 6, 7, 8], dtype = np.float32)
zs
zs.dtype

dtype('float32')

In [29]:
np.array([0.]*5)

array([0., 0., 0., 0., 0.])

In [31]:
np.array([1.]*4)

array([1., 1., 1., 1.])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.arange(10, 16)

array([10, 11, 12, 13, 14, 15])

In [45]:
np.arange(10., 16.)

array([10., 11., 12., 13., 14., 15.])

In [47]:
np.arange(1.5, 1.75, 0.05)

array([1.5 , 1.55, 1.6 , 1.65, 1.7 ])

In [49]:
np.arange(1.5, 1.8, 0.05)

array([1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 ])

In [51]:
np.arange(1.5, 1.75001, 0.05)

array([1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75])

In [57]:
np.linspace(1.5, 1.75, 5)

array([1.5   , 1.5625, 1.625 , 1.6875, 1.75  ])

In [59]:
np.linspace(1.5, 1.8, 7)

array([1.5 , 1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 ])

In [61]:
np.logspace(-1, -5, 5)

array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05])

1.2 Indexing and Slicing

In [64]:
xs = np.arange(10, 16)
print(xs)

[10 11 12 13 14 15]


In [66]:
xs[2]

12

In [70]:
xs = np.arange(10, 16)
print(xs[2:4])

[12 13]


In [76]:
r = np.array([11, 7, 19, 22])
print(r)

[11  7 19 22]


In [78]:
sli = r[1:3]
print(sli)

[ 7 19]


In [80]:
print(r)

[11  7 19 22]


In [82]:
r = np.array([11, 7, 19, 22])
sli = np.copy(r[1:3])
sli[0] = 55
print(sli)

[55 19]


In [84]:
r2 = np.copy(r)
r2[1] = 0
print(r2)

[11  0 19 22]


In [86]:
xs = np.arange(10, 16)
print(xs)

[10 11 12 13 14 15]


In [88]:
xs[:] = 7
print(xs)

[7 7 7 7 7 7]


1.3 Vectorization

In [91]:
xs = np.arange(10, 16)
ys = np.arange(20, 26)
print(xs)
print(ys)

[10 11 12 13 14 15]
[20 21 22 23 24 25]


In [93]:
print(xs + ys)

[30 32 34 36 38 40]


In [99]:
xs = list(range(10, 16))
ys = list(range(20, 26))
xs

[10, 11, 12, 13, 14, 15]

In [101]:
ys

[20, 21, 22, 23, 24, 25]

In [103]:
xs + ys

[10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25]

In [105]:
news = [x+y for x, y in zip(xs, ys)]
news

[30, 32, 34, 36, 38, 40]

In [109]:
xs = np.arange(10, 16)
ys = np.arange(20, 26)
print(xs*ys)

[200 231 264 299 336 375]


In [111]:
np.sum(xs*ys)

1705

In [113]:
xs = np.arange(10, 16)
print(xs)

[10 11 12 13 14 15]


In [115]:
print(2*xs)

[20 22 24 26 28 30]


In [117]:
xs = np.arange(10, 16)
print(1/xs)

[0.1        0.09090909 0.08333333 0.07692308 0.07142857 0.06666667]


In [119]:
import math
def f(x):
    return 1/math.sqrt(x**2+1)
ws = list(range(30, 36))
xs = list(range(10, 16))
tots = [w*f(x) for w,x in zip(ws, xs)]
print(tots)

[2.9851115706299676, 2.8066081273180745, 2.657455355319679, 2.5309844631963223, 2.422399699588928, 2.3281653683320878]


In [121]:
def fa(xs):
    return 1/np.sqrt(xs**2+1)
ws = np.arange(30, 36)
xs = np.arange(10, 16)
tots = ws*fa(xs)
print(tots)

[2.98511157 2.80660813 2.65745536 2.53098446 2.4223997  2.32816537]


2 Two-dimensional arrays

2.1 Creating

In [125]:
LL =[[11, 12, 13, 14], [ 15, 16, 17, 18], [19, 20, 21, 22]]

In [129]:
A = np.array(LL)
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [133]:
print(A)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]


In [135]:
B = np.array(LL, dtype=np.float64)
print(B)

[[11. 12. 13. 14.]
 [15. 16. 17. 18.]
 [19. 20. 21. 22.]]


In [137]:
B.dtype

dtype('float64')

In [139]:
A.size

12

In [141]:
A.ndim

2

In [143]:
A.shape

(3, 4)

In [145]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [147]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [149]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [151]:
B = np.array([1,4,9,7,2,8,5,6])
B.shape

(8,)

In [153]:
B = B.reshape((2,4))
B.shape

(2, 4)

In [155]:
B

array([[1, 4, 9, 7],
       [2, 8, 5, 6]])

In [157]:
A = np.arange(11, 23)
A = A.reshape((3, 4))
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [161]:
A = np.arange(11, 23).reshape(3,4)
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

2.2 Indexing and Slicing

In [164]:
LL = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21 ,22]]

In [166]:
LL[2][1]

20

In [168]:
A = np.arange(11,23).reshape(3,4)
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [170]:
A[2, 1]

20

In [172]:
A[1, 1:3]

array([16, 17])

In [174]:
A[1,:]

array([15, 16, 17, 18])

In [176]:
A[:,2]

array([13, 17, 21])

In [184]:
B = A[:2, 1:]
B

array([[12, 13, 14],
       [16, 17, 18]])

In [188]:
B[:,:] = 0
B

array([[0, 0, 0],
       [0, 0, 0]])

In [190]:
A

array([[11,  0,  0,  0],
       [15,  0,  0,  0],
       [19, 20, 21, 22]])

In [192]:
A = np.arange(11, 23).reshape(3, 4)
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

In [194]:
B = np.copy(A[:2,1:])
B[:,:] = 0
B

array([[0, 0, 0],
       [0, 0, 0]])

In [196]:
A

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22]])

2.3 Vectorization

In [199]:
A = np.arange(1,10).reshape(3,3)
B = np.arange(11,20).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [201]:
B

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [203]:
A+B

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [205]:
A*B

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [209]:
np.dot(A,B)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [211]:
A@B

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [213]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [215]:
np.trace(A)

15

In [217]:
A = np.arange(1, 10).reshape(3, 3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [219]:
for row in A:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [221]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [223]:
for column in A.T:
    print(column)

[1 4 7]
[2 5 8]
[3 6 9]


In [225]:
A/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [233]:
A = np.arange(1,10).reshape(3,3)
np.sum(A, axis=0)

array([12, 15, 18])

3 File input and output

In [238]:
%%writefile compl.in
x y
0.6 -6.2
1.6 9.3
1.8 16.

Overwriting compl.in


In [240]:
A = np.loadtxt("compl.in", skiprows = 1)
A

array([[ 0.6, -6.2],
       [ 1.6,  9.3],
       [ 1.8, 16. ]])

In [242]:
xs, ys = np.loadtxt("compl.in", skiprows = 1, unpack = True)
xs

array([0.6, 1.6, 1.8])

In [244]:
ys

array([-6.2,  9.3, 16. ])

In [246]:
xs = np.linspace(0, 1.8, 10)
ys = 4*xs**3-7
np.savetxt("compl2.out", (xs,ys))

In [248]:
xs

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [250]:
ys

array([-7.   , -6.968, -6.744, -6.136, -4.952, -3.   , -0.088,  3.976,
        9.384, 16.328])

In [252]:
A = np.column_stack((xs,ys))

In [254]:
A

array([[ 0.   , -7.   ],
       [ 0.2  , -6.968],
       [ 0.4  , -6.744],
       [ 0.6  , -6.136],
       [ 0.8  , -4.952],
       [ 1.   , -3.   ],
       [ 1.2  , -0.088],
       [ 1.4  ,  3.976],
       [ 1.6  ,  9.384],
       [ 1.8  , 16.328]])